DROP TABLE TESTEK2.SEGURO
CREATE TABLE TESTEK2TEST.SEGURO (
	ID VARCHAR2(100) NOT NULL,
	SEGURADOID INTEGER NOT NULL,
	MARCAMODELO VARCHAR2(100) NOT NULL,
	VALORVEICULO DECIMAL NOT NULL,
	VALORSEGURO DECIMAL NOT NULL,
	CONSTRAINT SEGURO_PK PRIMARY KEY (ID)
)
TABLESPACE USERS;


ALTER USER testek2test QUOTA 100M ON USERS;
 
GRANT UNLIMITED TABLESPACE TO testek2;

grant create session to testek2;


CREATE OR REPLACE TRIGGER SEGURO_on_insert
  BEFORE INSERT ON "TESTEK2".SEGURO
  FOR EACH ROW
BEGIN
  SELECT SEGURO_SEQ.nextval
  INTO :new.Id
  FROM dual;
END;


SHOW ERRORS TRIGGER SEGURO_on_insert;


INSERT INTO TESTEK2.SEGURO (ID, SEGURADOID, MARCAMODELO, VALORVEICULO, VALORSEGURO) VALUES ('3a2c031f-5321-4771-84c1-a2624594138b', 1, 'teste', 10000, 270.375)

SELECT * FROM TESTEK2.SEGURO

