CREATE TABLE "TESTEK2".SEGURO (
	ID int NOT NULL,
	MARCAMODELO VARCHAR2(100) NOT NULL,
	VALORVEICULO DECIMAL NOT NULL,
	VALORSEGURO DECIMAL NOT NULL,
	CONSTRAINT SEGURO_PK PRIMARY KEY (ID)
)
TABLESPACE USERS;


ALTER USER testek2 QUOTA 100M ON USERS;
 
GRANT UNLIMITED TABLESPACE TO testek2;